package aB.addressBookPackage;

/**
 * aB/addressBookPackage/notFound.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr
 * CEST
 */

public final class notFound extends org.omg.CORBA.UserException {

	public notFound() {
		super(notFoundHelper.id());
	} // ctor

	public notFound(String $reason) {
		super(notFoundHelper.id() + "  " + $reason);
	} // ctor

} // class notFound
