package aB.addressBookPackage;

/**
 * aB/addressBookPackage/notFoundHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from aB.idl Dienstag, 29. August 2006
 * 17.03 Uhr CEST
 */

public final class notFoundHolder implements org.omg.CORBA.portable.Streamable {
	public aB.addressBookPackage.notFound value = null;

	public notFoundHolder() {
	}

	public notFoundHolder(aB.addressBookPackage.notFound initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.addressBookPackage.notFoundHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.addressBookPackage.notFoundHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.addressBookPackage.notFoundHelper.type();
	}

}
