package aB.addressBookPackage;

/**
 * aB/addressBookPackage/sizeLimitReached.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from aB.idl Dienstag, 29. August 2006
 * 17.03 Uhr CEST
 */

public final class sizeLimitReached extends org.omg.CORBA.UserException {

	public sizeLimitReached() {
		super(sizeLimitReachedHelper.id());
	} // ctor

	public sizeLimitReached(String $reason) {
		super(sizeLimitReachedHelper.id() + "  " + $reason);
	} // ctor

} // class sizeLimitReached
