package aB.addressBookPackage;

/**
 * aB/addressBookPackage/sizeLimitReachedHolder.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.2" from aB.idl Dienstag, 29.
 * August 2006 17.03 Uhr CEST
 */

public final class sizeLimitReachedHolder implements
		org.omg.CORBA.portable.Streamable {
	public aB.addressBookPackage.sizeLimitReached value = null;

	public sizeLimitReachedHolder() {
	}

	public sizeLimitReachedHolder(
			aB.addressBookPackage.sizeLimitReached initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.addressBookPackage.sizeLimitReachedHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.addressBookPackage.sizeLimitReachedHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.addressBookPackage.sizeLimitReachedHelper.type();
	}

}
