package aB.addressBookPackage;

/**
 * aB/addressBookPackage/userExists.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr
 * CEST
 */

public final class userExists extends org.omg.CORBA.UserException {
	public String firstName = null;

	public userExists() {
		super(userExistsHelper.id());
	} // ctor

	public userExists(String _firstName) {
		super(userExistsHelper.id());
		firstName = _firstName;
	} // ctor

	public userExists(String $reason, String _firstName) {
		super(userExistsHelper.id() + "  " + $reason);
		firstName = _firstName;
	} // ctor

} // class userExists
