package aB.addressBookPackage;

/**
 * aB/addressBookPackage/userExistsHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.2" from aB.idl Dienstag, 29. August 2006
 * 17.03 Uhr CEST
 */

public final class userExistsHolder implements
		org.omg.CORBA.portable.Streamable {
	public aB.addressBookPackage.userExists value = null;

	public userExistsHolder() {
	}

	public userExistsHolder(aB.addressBookPackage.userExists initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.addressBookPackage.userExistsHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.addressBookPackage.userExistsHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.addressBookPackage.userExistsHelper.type();
	}

}
