package aB;

/**
 * aB/_addressBookStub.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public class _addressBookStub extends org.omg.CORBA.portable.ObjectImpl
		implements aB.addressBook {

	public void addEntry(aB.Entry p_entry)
			throws aB.addressBookPackage.userExists,
			aB.addressBookPackage.sizeLimitReached {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("addEntry", true);
			aB.EntryHelper.write($out, p_entry);
			$in = _invoke($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:aB/addressBook/userExists:1.0"))
				throw aB.addressBookPackage.userExistsHelper.read($in);
			else if (_id.equals("IDL:aB/addressBook/sizeLimitReached:1.0"))
				throw aB.addressBookPackage.sizeLimitReachedHelper.read($in);
			else
				throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			addEntry(p_entry);
		} finally {
			_releaseReply($in);
		}
	} // addEntry

	public aB.Contact getEntry(String surName)
			throws aB.addressBookPackage.notFound {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("getEntry", true);
			aB.SurNameHelper.write($out, surName);
			$in = _invoke($out);
			aB.Contact $result = aB.ContactHelper.read($in);
			return $result;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			if (_id.equals("IDL:aB/addressBook/notFound:1.0"))
				throw aB.addressBookPackage.notFoundHelper.read($in);
			else
				throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			return getEntry(surName);
		} finally {
			_releaseReply($in);
		}
	} // getEntry

	public void clear() {
		org.omg.CORBA.portable.InputStream $in = null;
		try {
			org.omg.CORBA.portable.OutputStream $out = _request("clear", true);
			$in = _invoke($out);
			return;
		} catch (org.omg.CORBA.portable.ApplicationException $ex) {
			$in = $ex.getInputStream();
			String _id = $ex.getId();
			throw new org.omg.CORBA.MARSHAL(_id);
		} catch (org.omg.CORBA.portable.RemarshalException $rm) {
			clear();
		} finally {
			_releaseReply($in);
		}
	} // clear

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:aB/addressBook:1.0" };

	public String[] _ids() {
		return (String[]) __ids.clone();
	}

	private void readObject(java.io.ObjectInputStream s)
			throws java.io.IOException {
		String str = s.readUTF();
		String[] args = null;
		java.util.Properties props = null;
		org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
				.string_to_object(str);
		org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
				._get_delegate();
		_set_delegate(delegate);
	}

	private void writeObject(java.io.ObjectOutputStream s)
			throws java.io.IOException {
		String[] args = null;
		java.util.Properties props = null;
		String str = org.omg.CORBA.ORB.init(args, props).object_to_string(this);
		s.writeUTF(str);
	}
} // class _addressBookStub
