package aB;

/**
 * aB/addressBookOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr
 * CEST
 */

public interface addressBookOperations {
	void addEntry(aB.Entry p_entry) throws aB.addressBookPackage.userExists,
			aB.addressBookPackage.sizeLimitReached;

	aB.Contact getEntry(String surName) throws aB.addressBookPackage.notFound;

	void clear();
} // interface addressBookOperations
