package aB;

/**
 * aB/addressBookHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public final class addressBookHolder implements
		org.omg.CORBA.portable.Streamable {
	public aB.addressBook value = null;

	public addressBookHolder() {
	}

	public addressBookHolder(aB.addressBook initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.addressBookHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.addressBookHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.addressBookHelper.type();
	}

}
