package aB;

/**
 * aB/addressBook.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public interface addressBook extends addressBookOperations,
		org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface addressBook
