package aB;

/**
 * aB/addressBookPOA.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public abstract class addressBookPOA extends org.omg.PortableServer.Servant
		implements aB.addressBookOperations, org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable _methods = new java.util.Hashtable();
	static {
		_methods.put("addEntry", new java.lang.Integer(0));
		_methods.put("getEntry", new java.lang.Integer(1));
		_methods.put("clear", new java.lang.Integer(2));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method,
			org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // aB/addressBook/addEntry
		{
			try {
				aB.Entry p_entry = aB.EntryHelper.read(in);
				this.addEntry(p_entry);
				out = $rh.createReply();
			} catch (aB.addressBookPackage.userExists $ex) {
				out = $rh.createExceptionReply();
				aB.addressBookPackage.userExistsHelper.write(out, $ex);
			} catch (aB.addressBookPackage.sizeLimitReached $ex) {
				out = $rh.createExceptionReply();
				aB.addressBookPackage.sizeLimitReachedHelper.write(out, $ex);
			}
			break;
		}

		case 1: // aB/addressBook/getEntry
		{
			try {
				String surName = aB.SurNameHelper.read(in);
				aB.Contact $result = null;
				$result = this.getEntry(surName);
				out = $rh.createReply();
				aB.ContactHelper.write(out, $result);
			} catch (aB.addressBookPackage.notFound $ex) {
				out = $rh.createExceptionReply();
				aB.addressBookPackage.notFoundHelper.write(out, $ex);
			}
			break;
		}

		case 2: // aB/addressBook/clear
		{
			this.clear();
			out = $rh.createReply();
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0,
					org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:aB/addressBook:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa,
			byte[] objectId) {
		return (String[]) __ids.clone();
	}

	public addressBook _this() {
		return addressBookHelper.narrow(super._this_object());
	}

	public addressBook _this(org.omg.CORBA.ORB orb) {
		return addressBookHelper.narrow(super._this_object(orb));
	}

} // class addressBookPOA
