package aB;

/**
 * aB/addressBookHelper.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

abstract public class addressBookHelper {
	private static String _id = "IDL:aB/addressBook:1.0";

	public static void insert(org.omg.CORBA.Any a, aB.addressBook that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static aB.addressBook extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			__typeCode = org.omg.CORBA.ORB.init().create_interface_tc(
					aB.addressBookHelper.id(), "addressBook");
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static aB.addressBook read(org.omg.CORBA.portable.InputStream istream) {
		return narrow(istream.read_Object(_addressBookStub.class));
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			aB.addressBook value) {
		ostream.write_Object((org.omg.CORBA.Object) value);
	}

	public static aB.addressBook narrow(org.omg.CORBA.Object obj) {
		if (obj == null)
			return null;
		else if (obj instanceof aB.addressBook)
			return (aB.addressBook) obj;
		else if (!obj._is_a(id()))
			throw new org.omg.CORBA.BAD_PARAM();
		else {
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
					._get_delegate();
			aB._addressBookStub stub = new aB._addressBookStub();
			stub._set_delegate(delegate);
			return stub;
		}
	}

	public static aB.addressBook unchecked_narrow(org.omg.CORBA.Object obj) {
		if (obj == null)
			return null;
		else if (obj instanceof aB.addressBook)
			return (aB.addressBook) obj;
		else {
			org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
					._get_delegate();
			aB._addressBookStub stub = new aB._addressBookStub();
			stub._set_delegate(delegate);
			return stub;
		}
	}

}
