package aB;

/**
 * aB/Contact.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public final class Contact implements org.omg.CORBA.portable.IDLEntity {
	private int[] ___number;
	private String ___email;
	private aB.ContactType __discriminator;
	private boolean __uninitialized = true;

	public Contact() {
	}

	public aB.ContactType discriminator() {
		if (__uninitialized)
			throw new org.omg.CORBA.BAD_OPERATION();
		return __discriminator;
	}

	public int[] number() {
		if (__uninitialized)
			throw new org.omg.CORBA.BAD_OPERATION();
		verifynumber(__discriminator);
		return ___number;
	}

	public void number(int[] value) {
		__discriminator = aB.ContactType.e_phoneNumber;
		___number = value;
		__uninitialized = false;
	}

	public void number(aB.ContactType discriminator, int[] value) {
		verifynumber(discriminator);
		__discriminator = discriminator;
		___number = value;
		__uninitialized = false;
	}

	private void verifynumber(aB.ContactType discriminator) {
		if (discriminator != aB.ContactType.e_phoneNumber)
			throw new org.omg.CORBA.BAD_OPERATION();
	}

	public String email() {
		if (__uninitialized)
			throw new org.omg.CORBA.BAD_OPERATION();
		verifyemail(__discriminator);
		return ___email;
	}

	public void email(String value) {
		__discriminator = aB.ContactType.e_email;
		___email = value;
		__uninitialized = false;
	}

	public void email(aB.ContactType discriminator, String value) {
		verifyemail(discriminator);
		__discriminator = discriminator;
		___email = value;
		__uninitialized = false;
	}

	private void verifyemail(aB.ContactType discriminator) {
		if (discriminator != aB.ContactType.e_email)
			throw new org.omg.CORBA.BAD_OPERATION();
	}

} // class Contact
