package aB;

/**
 * aB/ContactType.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public class ContactType implements org.omg.CORBA.portable.IDLEntity {
	private int __value;
	private static int __size = 2;
	private static aB.ContactType[] __array = new aB.ContactType[__size];

	public static final int _e_phoneNumber = 0;
	public static final aB.ContactType e_phoneNumber = new aB.ContactType(
			_e_phoneNumber);
	public static final int _e_email = 1;
	public static final aB.ContactType e_email = new aB.ContactType(_e_email);

	public int value() {
		return __value;
	}

	public static aB.ContactType from_int(int value) {
		if (value >= 0 && value < __size)
			return __array[value];
		else
			throw new org.omg.CORBA.BAD_PARAM();
	}

	protected ContactType(int value) {
		__value = value;
		__array[__value] = this;
	}
} // class ContactType
