package aB;

/**
 * aB/ContactTypeHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public final class ContactTypeHolder implements
		org.omg.CORBA.portable.Streamable {
	public aB.ContactType value = null;

	public ContactTypeHolder() {
	}

	public ContactTypeHolder(aB.ContactType initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.ContactTypeHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.ContactTypeHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.ContactTypeHelper.type();
	}

}
