package aB;

/**
 * aB/ContactTypeHelper.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

abstract public class ContactTypeHelper {
	private static String _id = "IDL:aB/ContactType:1.0";

	public static void insert(org.omg.CORBA.Any a, aB.ContactType that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static aB.ContactType extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			__typeCode = org.omg.CORBA.ORB.init().create_enum_tc(
					aB.ContactTypeHelper.id(), "ContactType",
					new String[] { "e_phoneNumber", "e_email" });
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static aB.ContactType read(org.omg.CORBA.portable.InputStream istream) {
		return aB.ContactType.from_int(istream.read_long());
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			aB.ContactType value) {
		ostream.write_long(value.value());
	}

}
