package aB;

/**
 * aB/ContactHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public final class ContactHolder implements org.omg.CORBA.portable.Streamable {
	public aB.Contact value = null;

	public ContactHolder() {
	}

	public ContactHolder(aB.Contact initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.ContactHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.ContactHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.ContactHelper.type();
	}

}
