package aB;

/**
 * aB/ContactHelper.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

abstract public class ContactHelper {
	private static String _id = "IDL:aB/Contact/Contact:1.0";

	public static void insert(org.omg.CORBA.Any a, aB.Contact that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static aB.Contact extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			org.omg.CORBA.TypeCode _disTypeCode0;
			_disTypeCode0 = aB.ContactTypeHelper.type();
			org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember[2];
			org.omg.CORBA.TypeCode _tcOf_members0;
			org.omg.CORBA.Any _anyOf_members0;

			// Branch for number (case label e_phoneNumber)
			_anyOf_members0 = org.omg.CORBA.ORB.init().create_any();
			aB.ContactTypeHelper
					.insert(_anyOf_members0, aB.ContactType.e_phoneNumber);
			_tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(
					org.omg.CORBA.TCKind.tk_long);
			_tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
					aB.DigitHelper.id(), "Digit", _tcOf_members0);
			_tcOf_members0 = org.omg.CORBA.ORB.init().create_sequence_tc(
					aB.digitAmount.value, _tcOf_members0);
			_tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
					aB.PhoneNumberHelper.id(), "PhoneNumber", _tcOf_members0);
			_members0[0] = new org.omg.CORBA.UnionMember("number", _anyOf_members0,
					_tcOf_members0, null);

			// Branch for email (case label e_email)
			_anyOf_members0 = org.omg.CORBA.ORB.init().create_any();
			aB.ContactTypeHelper.insert(_anyOf_members0, aB.ContactType.e_email);
			_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(0);
			_tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
					aB.EmailAddressHelper.id(), "EmailAddress", _tcOf_members0);
			_members0[1] = new org.omg.CORBA.UnionMember("email", _anyOf_members0,
					_tcOf_members0, null);
			__typeCode = org.omg.CORBA.ORB.init().create_union_tc(
					aB.ContactHelper.id(), "Contact", _disTypeCode0, _members0);
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static aB.Contact read(org.omg.CORBA.portable.InputStream istream) {
		aB.Contact value = new aB.Contact();
		aB.ContactType _dis0 = null;
		_dis0 = aB.ContactTypeHelper.read(istream);
		switch (_dis0.value()) {
		case aB.ContactType._e_phoneNumber:
			int _number[] = null;
			_number = aB.PhoneNumberHelper.read(istream);
			value.number(_number);
			break;
		case aB.ContactType._e_email:
			String _email = null;
			_email = aB.EmailAddressHelper.read(istream);
			value.email(_email);
			break;
		}
		return value;
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			aB.Contact value) {
		aB.ContactTypeHelper.write(ostream, value.discriminator());
		switch (value.discriminator().value()) {
		case aB.ContactType._e_phoneNumber:
			aB.PhoneNumberHelper.write(ostream, value.number());
			break;
		case aB.ContactType._e_email:
			aB.EmailAddressHelper.write(ostream, value.email());
			break;
		}
	}

}
