package aB;

/**
 * aB/emailLength.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public interface emailLength {
	public static final int value = (int) (40);
}
