package aB;

/**
 * aB/Entry.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public final class Entry implements org.omg.CORBA.portable.IDLEntity {
	public String surName = null;
	public String firstName = null;
	public aB.Gender gender = null;
	public aB.Contact contact = null;

	public Entry() {
	} // ctor

	public Entry(String _surName, String _firstName, aB.Gender _gender,
			aB.Contact _contact) {
		surName = _surName;
		firstName = _firstName;
		gender = _gender;
		contact = _contact;
	} // ctor

} // class Entry
