package aB;

/**
 * aB/EntryHelper.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

abstract public class EntryHelper {
	private static String _id = "IDL:aB/Entry/Entry:1.0";

	public static void insert(org.omg.CORBA.Any a, aB.Entry that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static aB.Entry extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;
	private static boolean __active = false;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			synchronized (org.omg.CORBA.TypeCode.class) {
				if (__typeCode == null) {
					if (__active) {
						return org.omg.CORBA.ORB.init().create_recursive_tc(_id);
					}
					__active = true;
					org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember[4];
					org.omg.CORBA.TypeCode _tcOf_members0 = null;
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(0);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
							aB.SurNameHelper.id(), "SurName", _tcOf_members0);
					_members0[0] = new org.omg.CORBA.StructMember("surName",
							_tcOf_members0, null);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_string_tc(0);
					_tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
							aB.FirstNameHelper.id(), "FirstName", _tcOf_members0);
					_members0[1] = new org.omg.CORBA.StructMember("firstName",
							_tcOf_members0, null);
					_tcOf_members0 = aB.GenderHelper.type();
					_members0[2] = new org.omg.CORBA.StructMember("gender",
							_tcOf_members0, null);
					_tcOf_members0 = aB.ContactHelper.type();
					_members0[3] = new org.omg.CORBA.StructMember("contact",
							_tcOf_members0, null);
					__typeCode = org.omg.CORBA.ORB.init().create_struct_tc(
							aB.EntryHelper.id(), "Entry", _members0);
					__active = false;
				}
			}
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static aB.Entry read(org.omg.CORBA.portable.InputStream istream) {
		aB.Entry value = new aB.Entry();
		value.surName = istream.read_string();
		value.firstName = istream.read_string();
		value.gender = aB.GenderHelper.read(istream);
		value.contact = aB.ContactHelper.read(istream);
		return value;
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			aB.Entry value) {
		ostream.write_string(value.surName);
		ostream.write_string(value.firstName);
		aB.GenderHelper.write(ostream, value.gender);
		aB.ContactHelper.write(ostream, value.contact);
	}

}
