package aB;

/**
 * aB/EntryHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public final class EntryHolder implements org.omg.CORBA.portable.Streamable {
	public aB.Entry value = null;

	public EntryHolder() {
	}

	public EntryHolder(aB.Entry initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.EntryHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.EntryHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.EntryHelper.type();
	}

}
