package aB;

/**
 * aB/Gender.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public class Gender implements org.omg.CORBA.portable.IDLEntity {
	private int __value;
	private static int __size = 2;
	private static aB.Gender[] __array = new aB.Gender[__size];

	public static final int _e_male = 0;
	public static final aB.Gender e_male = new aB.Gender(_e_male);
	public static final int _e_female = 1;
	public static final aB.Gender e_female = new aB.Gender(_e_female);

	public int value() {
		return __value;
	}

	public static aB.Gender from_int(int value) {
		if (value >= 0 && value < __size)
			return __array[value];
		else
			throw new org.omg.CORBA.BAD_PARAM();
	}

	protected Gender(int value) {
		__value = value;
		__array[__value] = this;
	}
} // class Gender
