package aB;

/**
 * aB/GenderHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

public final class GenderHolder implements org.omg.CORBA.portable.Streamable {
	public aB.Gender value = null;

	public GenderHolder() {
	}

	public GenderHolder(aB.Gender initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.GenderHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.GenderHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.GenderHelper.type();
	}

}
