package aB;

/**
 * aB/GenderHelper.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

abstract public class GenderHelper {
	private static String _id = "IDL:aB/Gender:1.0";

	public static void insert(org.omg.CORBA.Any a, aB.Gender that) {
		org.omg.CORBA.portable.OutputStream out = a.create_output_stream();
		a.type(type());
		write(out, that);
		a.read_value(out.create_input_stream(), type());
	}

	public static aB.Gender extract(org.omg.CORBA.Any a) {
		return read(a.create_input_stream());
	}

	private static org.omg.CORBA.TypeCode __typeCode = null;

	synchronized public static org.omg.CORBA.TypeCode type() {
		if (__typeCode == null) {
			__typeCode = org.omg.CORBA.ORB.init()
					.create_enum_tc(aB.GenderHelper.id(), "Gender",
							new String[] { "e_male", "e_female" });
		}
		return __typeCode;
	}

	public static String id() {
		return _id;
	}

	public static aB.Gender read(org.omg.CORBA.portable.InputStream istream) {
		return aB.Gender.from_int(istream.read_long());
	}

	public static void write(org.omg.CORBA.portable.OutputStream ostream,
			aB.Gender value) {
		ostream.write_long(value.value());
	}

}
