package aB;

/**
 * aB/PhoneNumberHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from aB.idl Dienstag, 29. August 2006 17.03 Uhr CEST
 */

// should be 0..9
public final class PhoneNumberHolder implements
		org.omg.CORBA.portable.Streamable {
	public int value[] = null;

	public PhoneNumberHolder() {
	}

	public PhoneNumberHolder(int[] initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = aB.PhoneNumberHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		aB.PhoneNumberHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return aB.PhoneNumberHelper.type();
	}

}
